### ISSUE TITLE
Error while compiling on mac using cpp

### ISSUE THREAD

**Issue by SuperGameMaker** [DleanJeans/hscript-plus#1]
I think the same error happens on all c++ targets:

```
Error: ./src/hscript/plus/ClassUtil.cpp:82:19: error: void function '_hx_run' should not return a value [-Wreturn-type]
HXDLIN(  30)                                            return ::Reflect_obj::callMethod(_this,field,method1);
```

**Comment by DleanJeans** [comment]
I can't get my tests to print some messages on c++ target for some reasons (never did this before, oops!). So yeah, I don't know if the fix works or not. But until then check it out:
```
haxelib git hscript-plus https://github.com/DleanJeans/hscript-plus/ fix-issue-1
```
Run the command to install it. Tell me if it works or not.
Thanks!

**Comment by SuperGameMaker** [comment]
it build with the change, however when I run the sample script (the one on the readme) I get the following error:

ScriptState.hx:85: EInvalidAccess(name)

it works fine on neko/html5 target, but not on cpp
